# Generated by Django 4.0.5 on 2022-06-14 18:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='passenger_trip',
            fields=[
                ('passenger_trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_distance', models.IntegerField(max_length=100)),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('estimated_end_time', models.DateTimeField(default=datetime.datetime(2022, 6, 14, 18, 49, 49, 301974))),
                ('passenger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.passenger')),
            ],
        ),
    ]
