# Generated by Django 4.0.5 on 2022-06-14 18:21

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_passenger_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger_trip',
            name='estimated_end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 18, 51, 48, 700097)),
        ),
        migrations.AlterField(
            model_name='passenger_trip',
            name='total_distance',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
