# Generated by Django 4.0.5 on 2022-06-15 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_passenger_surname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger_trip',
            name='estimated_end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 16, 16, 18, 85861)),
        ),
        migrations.AlterField(
            model_name='passenger_trip',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 15, 46, 18, 85867)),
        ),
    ]
