# Generated by Django 4.0.5 on 2022-06-15 15:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_passenger_trip_estimated_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger_trip',
            name='estimated_end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 16, 18, 21, 295097, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='passenger_trip',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 15, 48, 21, 295093, tzinfo=utc)),
        ),
    ]
